spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope: email, profile

auth:
  token:
    secretKey: asdf234asdfasdfasdf123asfdzxcvvzxvca234sadfasdfasfdasfd
    accessTokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8080
      - http://localhost:3000
  cors:
    allowed-origins:
    - http://localhost:8080,
    - http://localhost:3000
    allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    allowed-headers: '*'
    max-age: 3600