spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: email, profile

auth:
  token:
    secretKey: ${AUTH_TOKEN_SECRET_KEY}
    accessTokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8080
      - http://localhost:3000
      - http://localhost:3001
  cors:
    allowed-origins:
      - http://localhost:8080,
      - http://localhost:3000
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers: '*'
    max-age: 3600