spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
            scope: email, profile

auth:
  token:
    secretKey: sadfasdfsafdsadfsadfsafdsafdsafdsafdsafdsafdsafdsafdsafdsafsadfsadfsafdsadfsafdsadf
    accessTokenExpiry: 9900000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8080
      - http://localhost:3000
      - http://localhost:3001
      - https://www.moneyminder.co.kr
  cors:
    allowed-origins:
      - http://localhost:8080
      - http://localhost:3000
      - http://localhost:3001
      - https://www.moneyminder.co.kr
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers: '*'
    max-age: 3600


