spring:
  profiles:
    include: oauth2
    active: local
    group:
      local: local, common
      dev: dev, common


  # 공통 설정
---
spring:
  profiles: common

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER_NAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  management:
    endpoints:
      web:
        exposure:
          include: "*"

server:
  forward-headers-strategy: native

