spring:
  profiles:
    include: oauth2
    active: local
    group:
      local: local, common
      dev: dev, common


  # 공통 설정
---
spring:
  config:
    activate:
      on-profile: common

  mail:
    host: smtp.gmail.com
    port: 587
    username: rkddms123456@gmail.com
    password: tfsk xapo plcz umtw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

management:
  endpoints:
    web:
      exposure:
        include: '*'



