version: '3.8'
networks:
  moneyMinder-network:
    driver: bridge

services:
  moneyMinder-backend:
    build:
      context: .
      dockerfile: config/deploy/be-Dockerfile
    container_name: moneyMinder-backend
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /home/ec2-user/backend/log:/app/moneyMinder/log
    networks:
      - moneyMinder-network

  moneyMinder-frontend:
    build:
      context: .
      dockerfile: config/deploy/fe-Dockerfile
    container_name: moneyMinder-frontend
    restart: always
    ports:
      - "3001:80"
    networks:
      - moneyMinder-network

  nginx:
    build:
      context: .
      dockerfile: config/deploy/nginx.conf  # nginx.conf가 있는 경로로 지정
    container_name: moneyMinder-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ec2-user/cert-backup/live:/etc/letsencrypt/live  # 인증서 마운트
    networks:
      - moneyMinder-network
