version: '3.8'
networks:
  moneyMinder-network:
    driver: bridge

services:
  moneyMinder-backend-blue:
    image: gangeunlee/moneyminder-backend:latest
    container_name: moneyMinder-backend-blue
    restart: always
    ports:
      - "8080:8080"  # Blue 인스턴스
    volumes:
      - /home/ec2-user/backend/log:/app/moneyMinder/log
    networks:
      - moneyMinder-network
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: dev
    env_file:
      - .env

  moneyMinder-backend-green:
    image: gangeunlee/moneyminder-backend:latest
    container_name: moneyMinder-backend-green
    restart: always
    ports:
      - "8081:8080"  # Green 인스턴스
    volumes:
      - /home/ec2-user/backend/log:/app/moneyMinder/log
    networks:
      - moneyMinder-network
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: dev
    env_file:
      - .env

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /home/ec2-user/moneyminder/config/deploy/nginx.conf:/etc/nginx/nginx.conf
      - /home/ec2-user/moneyminder/logs/nginx/:/var/log/nginx/
      - /etc/letsencrypt/live/api.moneyminder.co.kr:/etc/letsencrypt/live/api.moneyminder.co.kr
      - /etc/letsencrypt/archive/api.moneyminder.co.kr:/etc/letsencrypt/archive/api.moneyminder.co.kr
    networks:
      - moneyMinder-network
    environment:
      TZ: Asia/Seoul
    depends_on:
      - certbot

