name: FE CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    if: startsWith(github.event.head_commit.message, '[FE]')
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      - name: Node.js 16 설치
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: 프론트엔드 빌드
        run: |
          cd frontend
          npm install
          npm run dev

      - name: AWS 접근 권한 설정
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: ap-northeast-2

      - name: S3에 배포
        run: |
          aws s3 sync ./frontend/dist s3://${{ secrets.AWS_S3_BUCKET_NAME }} 

      - name: CloudFront 캐시 무효화
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }} --paths "/*"
